<div class="middle-menu">
    <div class="menu__column_1">
        <h4><?php echo __('KAN VI HJELPE DEG')?></h4>
        <ul>
            <li><a href="#"><?php echo __('Om oss')?></a></li>
            <li><a href="#"><?php echo __('Kjøp, salg og leveringsbetingelse ')?></a></li>
            <li><a href="#"><?php echo __('Kontakt')?></a></li>

        </ul>
    </div>
    <div class="menu__column_2">
        <h4><?php echo __('HVORFOR SCANHOLM?')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('Sikker betaling')?>"><?php echo __('Sikker betaling')?></a></li>
            <li><a href="#" title="<?php echo __('1-3 dagers frakt')?>"><?php echo __('1-3 dagers frakt')?></a></li>
            <li><a href="#" id="open-map" title="<?php echo __('Kvalitesgaranti')?>"><?php echo __('Kvalitesgaranti')?></a></li>
            <li><a href="#" title="<?php echo __('90 dagers angrefrist')?>"><?php echo __('90 dagers angrefrist')?></a></li>
        </ul>
    </div>
    <div class="menu__column_3">
        <h4><?php echo __('TYPE LINSER')?></h4>
        <ul>
            <li><a href="#" title="<?php echo __('dagslinser')?>"><?php echo __('Dagslinser')?></a></li>
            <li><a href="#" title="<?php echo __('maned')?>"><?php echo __('Månedslinser')?></a></li>
            <li><a href="#" id="open-map" title="<?php echo __('Ukelinser')?>"><?php echo __('Ukelinser')?></a></li>
        </ul>
    </div>
    <div class="menu__column_4">
        <img src="<?php echo $block->getViewFileUrl('images/lenspower_headerlogo.png')?>">
        <ul>

            <li><p>Gaten 12,3174 Sted, Norway</p></li>
            <li><p>Tlf. 900 000 00</p></li>
            <li><p>E-post: post@mail.com</p></li>
            <li><p>Orgnr. 900 000 0000</p></li>
        </ul>
    </div>
</div>